# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_pixel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='z',
            field=models.FloatField(),
        ),
    ]
