# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200306_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='hexa',
            name='grass',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexa',
            name='hills',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexa',
            name='mountains',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexa',
            name='water',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexa',
            name='wood',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
