# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200128_1820'),
        ('recon', '0002_paw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacking', models.BooleanField()),
                ('hit_chance', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon.Animal')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='paw',
            name='animal',
        ),
        migrations.DeleteModel(
            name='Paw',
        ),
    ]
