# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_auto_20200307_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='hits',
            field=models.IntegerField(null=True),
        ),
    ]
