# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0004_auto_20200307_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
