# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-08 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0005_auto_20200308_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='running',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
