# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-08 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0006_hunt_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='running',
        ),
    ]
