# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0007_remove_hunt_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
