# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0008_hunt_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='slot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
