# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0010_auto_20200310_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='light_blood',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
