# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-05 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0003_auto_20180309_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('quality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Armors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('steel', models.FloatField()),
                ('wood', models.FloatField()),
                ('leather', models.FloatField()),
                ('min_movement', models.FloatField()),
                ('absorb', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('max_stack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('max_stack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('equip', models.IntegerField(blank=True, null=True)),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Armor')),
                ('consume_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ConsumeItems')),
                ('craft_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.CraftItems')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Semiproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('steel', models.FloatField()),
                ('wood', models.FloatField()),
                ('leather', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('quality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('steel', models.FloatField()),
                ('wood', models.FloatField()),
                ('leather', models.FloatField()),
                ('min_movement', models.FloatField()),
                ('defence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('dur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('steel', models.FloatField()),
                ('wood', models.FloatField()),
                ('leather', models.FloatField()),
                ('focus', models.FloatField()),
                ('focus_offset', models.FloatField()),
                ('attack', models.FloatField()),
                ('defence', models.FloatField()),
                ('dmg', models.FloatField()),
                ('dmg_offset', models.FloatField()),
                ('stun', models.FloatField()),
                ('deattack', models.FloatField()),
                ('twohand', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='static',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapons'),
        ),
        migrations.AddField(
            model_name='shield',
            name='static',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Shields'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='semiproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Semiproduct'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Shield'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapon'),
        ),
        migrations.AddField(
            model_name='armor',
            name='static',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Armors'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('player', 'pos')]),
        ),
    ]
