# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('steel', models.IntegerField()),
                ('wood', models.IntegerField()),
                ('leather', models.IntegerField()),
                ('focuse', models.IntegerField()),
                ('focuse_offset', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('dmg', models.IntegerField()),
                ('dmg_offset', models.IntegerField()),
                ('stun', models.IntegerField()),
                ('deattack', models.IntegerField()),
            ],
        ),
    ]
