# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_weapons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapons',
            old_name='focuse',
            new_name='focus',
        ),
        migrations.RenameField(
            model_name='weapons',
            old_name='focuse_offset',
            new_name='focus_offset',
        ),
    ]
