# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_armors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armors',
            name='armor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='armors',
            name='min_movement',
            field=models.FloatField(),
        ),
    ]
