# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180307_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('steel', models.FloatField()),
                ('wood', models.FloatField()),
                ('leather', models.FloatField()),
                ('min_movement', models.FloatField()),
                ('defence', models.FloatField()),
            ],
        ),
    ]
