# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180225_1849'),
        ('inventory', '0007_shields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('consume_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ConsumeItems')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('dur', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('static', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapons')),
            ],
        ),
        migrations.AddField(
            model_name='inventary',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapon'),
        ),
    ]
