# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180309_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventary',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
