# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventary',
            name='consume_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ConsumeItems'),
        ),
        migrations.AlterField(
            model_name='inventary',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapon'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapons'),
        ),
    ]
