# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180309_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='static',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Weapons'),
            preserve_default=False,
        ),
    ]
