# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180309_2242'),
        ('inventory', '0012_auto_20180309_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventary',
            name='pos',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='inventary',
            unique_together=set([('player', 'pos')]),
        ),
    ]
