# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180310_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventary',
            new_name='Inventory',
        ),
    ]
