# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20180312_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armors',
            old_name='dmg',
            new_name='absorb',
        ),
    ]
