# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180312_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Armor'),
        ),
    ]
