# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_shield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='shields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Shield'),
        ),
    ]
