# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_player',
            field=models.BooleanField(default=False),
        ),
    ]
