# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180225_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='second_player',
        ),
        migrations.AddField(
            model_name='user',
            name='active_player',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
